(define (problem tudoAbertoAceso)
    (:domain agenteDeSeguranca)
    (:objects Sala1 Sala2 Sala3 Sala4 Sala5 Sala6 Corredor
    Janela1a Janela1b Janela2 Janela3 Janela4a Janela4b Janela5 Janela6
    Porta1 Porta2 Porta3 Porta4 Porta5 Porta6 Luz1 Luz2 Luz3 Luz4 Luz5 Luz6)
    (:init (Em Corredor) (Sala Corredor) 
    (Sala Sala1) (Sala Sala2) (Sala Sala3) (Sala Sala4) (Sala Sala5) 
    (Sala Sala6) (Porta Porta1) (Porta Porta2) (Porta Porta3) (Porta Porta4) 
    (Porta Porta5) (Porta Porta6) (Luz Luz1) (Luz Luz2) (Luz Luz3) (Luz Luz4)
    (Luz Luz5) (Luz Luz6) (Janela Janela1a) (Janela Janela1b) (Janela Janela2)
    (Janela Janela3) (Janela Janela4a) (Janela Janela4b) (Janela Janela5) 
    (Janela Janela6) (Pertence Janela1a Sala1) (Pertence Janela1b Sala1)
    (Pertence Luz1 Sala1) (Pertence Janela2 Sala2) (Pertence Luz2 Sala2)
    (Pertence Janela3 Sala3) (Pertence Luz3 Sala3) (Pertence Janela4a Sala4)
    (Pertence Janela4b Sala4) (Pertence Luz4 Sala4) (Pertence Janela5 Sala5)
    (Pertence Luz5 Sala5) (Pertence Janela6 Sala6) (Pertence Luz6 Sala6)
    (TemAcesso Porta1 Sala2 Sala1) (TemAcesso Porta2 Sala3 Sala2) 
    (TemAcesso Porta3 Corredor Sala3) (TemAcesso Porta4 Sala5 Sala4)
    (TemAcesso Porta5 Sala6 Sala5) (TemAcesso Porta6 Corredor Sala6)
    (Aberta Porta1) (Aberta Porta2) (Aberta Porta3) (Aberta Porta4) 
    (Aberta Porta5) (Aberta Porta6) (Aberta Janela1a) (Aberta Janela1b) 
    (Aberta Janela2) (Aberta Janela3) (Aberta Janela4a) (Aberta Janela4b) 
    (Aberta Janela5) (Aberta Janela6) (Acesa Luz1) (Acesa Luz2) (Acesa Luz3) 
    (Acesa Luz4) (Acesa Luz5) (Acesa Luz6) )
    ;Trancar Salas 1 e 4 (da Ponta)
    (:goal (and (Fechada Janela1a) (Fechada Janela1b) (Aberta Janela2) 
    (Aberta Janela3) (Fechada Janela4a) (Fechada Janela4b) (Aberta Janela5) 
    (Aberta Janela6) (Fechada Porta1) (Aberta Porta2) (Aberta Porta3) 
    (Fechada Porta4) (Aberta Porta5) (Aberta Porta6) (Apagada Luz1) 
    (Acesa Luz2) (Acesa Luz3) (Apagada Luz4) (Acesa Luz5) 
    (Acesa Luz6) ))
)